### ISSUE TITLE
use Bloom filter to check exist event

### ISSUE THREAD

**Issue by ZigBalthazar** [dezh-tech/immortal#31]
We should use an in-memory bloom filter to check if an event exists in the database before writing it. This will help reduce the load on the database. Additionally, we may be able to ignore retrieval requests for deleted events (as per NIP-9) by removing the event data and only keeping the deleted_at and id, (maybe) We need a cold start for our bloom filter service to load existing data during bootstrapping.

**Comment by kehiy** [comment]
we can't check if some requested events are already deleted since we get queries as filters and its not logical to iterate over the `_ids_` field. so, we can only check if new events are already stored.
